name: Test Swift

on:
  push:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'
  pull_request:
    paths:
      - 'Swift/**'
      - '.github/workflows/Swift.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5"

    - name: Build
      working-directory: Swift
      run: swift build

    - name: Test
      working-directory: Swift
      run: swift test

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
